excluded:
- Pods
- Register
- Frameworks
- Dependencies
- SnapshotHelper.swift

disabled_rules:
- cyclomatic_complexity
- multiple_closures_with_trailing_closure
- todo
- void_function_in_ternary
- unused_optional_binding

analyzer_rules:
- unused_import

opt_in_rules:
- sorted_imports
- strong_iboutlet
- private_action
- private_outlet

trailing_whitespace:
  ignores_empty_lines: true
vertical_whitespace:
  max_empty_lines: 2
line_length:
  warning: 180
  ignores_urls: true
  ignores_interpolated_strings: true
large_tuple:
  warning: 3
  error: 4
identifier_name:
  max_length:
   warning: 60
  min_length:
    warning: 1
    error: 1
  allowed_symbols: ["_"]
type_name:
  allowed_symbols: ["_"]
  max_length:
    warning: 50
nesting:
  type_level: 2

custom_rules:
  todo_format:
    match_kinds: comment
    severity: warning
    message: >
        TODO comments must have a valid ticket number raised in Jira.
        Please use the format:
        // TODO: DCMAW-000
    regex: "(?i)(todo(?!(.*dcmaw-\\d{2,})))"
    
