# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

submission_information({
  add_id_info_serves_ads: true,
})
precheck_include_in_app_purchases(false)
