name: Manual UI Test

on:
  workflow_dispatch:

jobs:
  test_ui:
    name: Manual Action
    uses: ./.github/workflows/composite-actions/ui-test.yml
    with:
      test_branch: '${{ github.ref_name }}'
    secrets: inherit
