name: iOS Deploy - develop

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  run_unit_tests:
    name: Run Unit Tests for develop branch
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit

  test_build_config:
    name: Run Deployment Tests
    uses: ./.github/workflows/config-test.yml
    with:
      configuration: "Build"
      app_check: true
    secrets: inherit

  test_staging_config:
    name: Run Deployment Tests
    uses: ./.github/workflows/config-test.yml
    with:
      configuration: "Staging"
    secrets: inherit

  test_ui:
    name: Run Deployment Tests
    uses: ./.github/workflows/ui-test.yml
    secrets: inherit

  deploy_build_app:
    needs: [ test_build_config, test_ui ]
    name: Deploy App
    uses: ./.github/workflows/deploy.yml
    with:
      configuration: "Build"
      app_check: true
    secrets: inherit

  deploy_staging_app:
    needs: [ test_staging_config, test_ui ]
    name: Deploy App
    uses: ./.github/workflows/deploy.yml
    with:
      configuration: "Staging"
    secrets: inherit
