name: Manual UI Test

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test_ui:
    name: Run Deployment Tests
    uses: ./.github/workflows/config-test.yml
    with:
      configuration: "Build"
      app_check: true
    secrets: inherit
