on:
  workflow_call:
    inputs:
      build_products_artifact_id:
        required: true
        type: string

jobs:
  run_unit_tests_and_send_coverage_report:
    name: OneLoginUnit
    runs-on: macos-26
    steps:
      - name: Add Path Globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v4
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0
          token: ${{ secrets.MODULE_FETCH_TOKEN }}

      - name: Download Fastlane build_products
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # pin@v8.1
        with:
          artifact-ids: ${{ inputs.build_products_artifact_id }}
          path: ${{ github.workspace }}/fastlane/test_output/

      - name: Unzip Fastlane build_products          
        run: unzip -q ${{ github.workspace }}/fastlane/test_output/build_products.zip

      - name: Bundler install
        run: bundle install

      - name: Install sonar scanner
        run: brew install sonar-scanner

      - name: Run Tests and Send Coverage Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LC_ALL: "en_US.UTF-8"
          LANG: "en_US.UTF-8"
          GIT_CONFIG_NOSYSTEM: "true"
          GIT_CONFIG_GLOBAL: '${{ github.workspace }}/scripts-configs/override-git-config'
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          TEST_PLAN: "OneLoginUnit"
        run: |
          xctestrun=$(find . -name "*.xctestrun" | grep -i "${TEST_PLAN}")
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          bundle exec fastlane testWithoutBuilding scheme:"OneLoginBuild" \
            xctestrun:"${xctestrun}" \
            workspace:${{ github.workspace }} \
            source_branch:${{ github.head_ref }} \
            target_branch:${{ github.base_ref }} \
            pr_number:$pull_number

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@7a5fffe8e523c40e0c740b6bc2712ab503e52efa # pin@v1.2.1
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload OneLoginUnit.xcresult
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v4
        with:
          name: OneLoginUnit.xcresult
          path: ${{ github.workspace }}/fastlane/test_output/OneLoginBuild.xcresult
          retention-days: 1
          compression-level: 0