on:
  workflow_call:
    inputs:
      build_products_artifact_id:
        required: true
        type: string

jobs:
  run_snapshot_tests:
    name: OneLoginSnapshot
    runs-on: macos-26
    steps:
      - name: Add Path Globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v4
        with:
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0
          token: ${{ secrets.MODULE_FETCH_TOKEN }}

      - name: Download Fastlane build_products
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # pin@v8.1
        with:
          artifact-ids: ${{ inputs.build_products_artifact_id }}
          path: ${{ github.workspace }}/fastlane/test_output/

      - name: Unzip Fastlane build_products          
        run: unzip -q ${{ github.workspace }}/fastlane/test_output/build_products.zip

      - name: Bundler install
        run: bundle install

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LC_ALL: "en_US.UTF-8"
          LANG: "en_US.UTF-8"
          GIT_CONFIG_NOSYSTEM: "true"
          GIT_CONFIG_GLOBAL: '${{ github.workspace }}/scripts-configs/override-git-config'
          TEST_PLAN: "OneLoginSnapshot"
        run: |
          xctestrun=$(find . -name "*.xctestrun" | grep -i "${TEST_PLAN}")

          bundle exec fastlane testWithoutBuildingWithoutCoverage scheme:"OneLoginBuild" \
            xctestrun:"${xctestrun}"

      - name: Upload OneLoginSnapshot.xcresult
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v4
        with:
          name: OneLoginSnapshot.xcresult
          path: ${{ github.workspace }}/fastlane/test_output/OneLoginBuild.xcresult
          retention-days: 1
          compression-level: 0