on:
  workflow_call:
    inputs:
      test_branch:
        type: string
        default: 'develop'

jobs:
  run_ui_tests:
    name: OneLoginUI
    runs-on: macos-26
    steps:
      - name: Add Path Globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v4
        with:
          ref: ${{ inputs.test_branch }}
          lfs: 'true'
          submodules: 'true'
          fetch-depth: 0
          token: ${{ secrets.MODULE_FETCH_TOKEN }}

      - name: Download Fastlane build_products
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # pin@v8.1
        with:
          artifact-ids: build_products.zip
          path: ${{ github.workspace }}/fastlane/test_output/

      - name: Unzip Fastlane build_products
        run: unzip -q ${{ github.workspace }}/fastlane/test_output/build_products.zip

      - name: Bundler install
        run: bundle install

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LC_ALL: "en_US.UTF-8"
          LANG: "en_US.UTF-8"
          GIT_CONFIG_NOSYSTEM: "true"
          GIT_CONFIG_GLOBAL: '${{ github.workspace }}/scripts-configs/override-git-config'
          TEST_PLAN: "OneLoginUI"
        run: |
          xctestrun=$(find . -name "*.xctestrun" | grep -i "${TEST_PLAN}")

          bundle exec fastlane testWithoutBuildingWithoutCoverageForUITests scheme:"OneLoginBuild" \
            configuration:"Debug" \
            xctestrun: "${xctestrun}"

      - name: Make Artifact
        if: failure()
        run: |
          cd ./fastlane
          zip -rq UITestArtifact test_output -x "test_output/report.junit"

      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v4
        with:
          name: UITestArtifact
          path: ./fastlane/UITestArtifact.zip
          retention-days: 1
          compression-level: 0

      - name: Upload OneLoginUI.xcresult
        if: success() || failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # pin@v4
        with:
          name: OneLoginUI.xcresult
          path: ${{ github.workspace }}/fastlane/test_output/OneLoginBuild.xcresult
          retention-days: 1
          compression-level: 0